name: CreditCard
description: Example use for Credit Card Flutter package

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  credit_card:
    path: ../
  cupertino_icons: ^0.1.2
  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

 
